[supabase]
url = "https://jhksvhujsrbkeyzpvpog.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impoa3N2aHVqc3Jia2V5enB2cG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU4ODk2MzksImV4cCI6MjA4MTQ2NTYzOX0.JXFl-wPBInDlnc_pslt5xEH2ZpmYEBM7VmiPSjhlkXk"